spring:
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:32771/itemsharingdatabase"
    username: "root"
    password: "{cipher}8c85468cca1871204307123e34fb1764a302eebfb0c6c561a7f80d61e59dc893"
    testWhileIdle: true
    validationQuery: "SELECT 1"
       
security:
  basic:
    enable: false
    
server:
  port: 8082
